server:
  port: 5601

spring:
  profiles: test
  application:
    name: microservice-config-client-10

eureka:
  client:
    server-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
